### PR TITLE
Port code over to Windows

### PR DESCRIPTION
**Pull request by Kazuki-TAKEDA**
Porting code such as file mapping over to Windows

### CODE REVIEW

**Comment by mfranberg** [comment]
This looks excellent! I don't have access to a windows machine, but I enabled github actions and added the windows platform, but it doesn't seem to build: https://github.com/mfranberg/libplinkio/pull/28

Maybe you can have a look? You can rebase with latest master and add windows in the .github/workflows/cmake.yml file:
```
- os: windows-latest
  compiler: cl
  target: Windows
```

**Comment by Kazuki-TAKEDA** [comment]
Sorry, my pull request is only tested for MinGW gcc, not for MSVC.

**Comment by Kazuki-TAKEDA** [comment]
I built upstream code with MinGW gcc after a rebase and I got some errors during build.
It seems to happen due to code changes in upstream.
I'll fix it.

**Comment by Kazuki-TAKEDA** [comment]
All compiler errors has been fixed.

**Comment by mfranberg** [comment]
Looks fantastic, thank you for fixing all of this!

**Pull request merged**
